/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ProcessRequest } from '../models';
// @ts-ignore
import { ProcessResponse } from '../models';
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Process list of documents images and return extracted data
         * @param {ProcessRequest} processRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProcess: async (processRequest: ProcessRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'processRequest' is not null or undefined
            if (processRequest === null || processRequest === undefined) {
                throw new RequiredError('processRequest','Required parameter processRequest was null or undefined when calling apiProcess.');
            }
            const localVarPath = `/api/process`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof processRequest !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(processRequest !== undefined ? processRequest : {}) : (processRequest || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Process list of documents images and return extracted data
         * @param {ProcessRequest} processRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiProcess(processRequest: ProcessRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProcessResponse>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiProcess(processRequest, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Process list of documents images and return extracted data
         * @param {ProcessRequest} processRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiProcess(processRequest: ProcessRequest, options?: any): AxiosPromise<ProcessResponse> {
            return DefaultApiFp(configuration).apiProcess(processRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Process list of documents images and return extracted data
     * @param {ProcessRequest} processRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiProcess(processRequest: ProcessRequest, options?: any) {
        return DefaultApiFp(this.configuration).apiProcess(processRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
