/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ChosenDocumentTypeResult } from './chosen-document-type-result';
import { DocumentImageResult } from './document-image-result';
import { DocumentTypesCandidatesResult } from './document-types-candidates-result';
import { GraphicsResult } from './graphics-result';
import { ImagesResult } from './images-result';
import { LexicalAnalysisResult } from './lexical-analysis-result';
import { StatusResult } from './status-result';
import { TextDataResult } from './text-data-result';
import { TextResult } from './text-result';

/**
 * list with result objects
 * @export
 * @interface ContainerList
 */
export interface ContainerList {
    /**
     * 
     * @type {Array<DocumentImageResult | TextResult | StatusResult | TextDataResult | GraphicsResult | LexicalAnalysisResult | ChosenDocumentTypeResult | DocumentTypesCandidatesResult | ImagesResult>}
     * @memberof ContainerList
     */
    List: Array<DocumentImageResult | TextResult | StatusResult | TextDataResult | GraphicsResult | LexicalAnalysisResult | ChosenDocumentTypeResult | DocumentTypesCandidatesResult | ImagesResult>;
}


