/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CheckResult } from './check-result';

/**
 * 
 * @export
 * @interface DetailsRFID
 */
export interface DetailsRFID {
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsRFID
     */
    overallStatus: CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsRFID
     */
    AA: CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsRFID
     */
    BAC: CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsRFID
     */
    CA: CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsRFID
     */
    PA: CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsRFID
     */
    PACE: CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof DetailsRFID
     */
    TA: CheckResult;
}


