/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeviceInfo
 */
export interface DeviceInfo {
    /**
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    app_name?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    version?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    license_id?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    license_serial?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    valid_until?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceInfo
     */
    server_time?: string;
}


