/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LCID } from './lcid';
import { RectangleCoordinates } from './rectangle-coordinates';
import { StringRecognitionResult } from './string-recognition-result';
import { TextFieldType } from './text-field-type';

/**
 * 
 * @export
 * @interface DocVisualExtendedField
 */
export interface DocVisualExtendedField {
    /**
     * 
     * @type {TextFieldType}
     * @memberof DocVisualExtendedField
     */
    wFieldType: TextFieldType;
    /**
     * 
     * @type {LCID}
     * @memberof DocVisualExtendedField
     */
    wLCID: LCID;
    /**
     * Array of recognizing probabilities for a each line of text field. Only for Result.VISUAL_TEXT and Result.MRZ_TEXT results.
     * @type {Array<StringRecognitionResult>}
     * @memberof DocVisualExtendedField
     */
    StringsResult?: Array<StringRecognitionResult>;
    /**
     * Text field data in UTF8 format. Results of reading different lines of a multi-line field are separated by \'^\'
     * @type {string}
     * @memberof DocVisualExtendedField
     */
    Buf_Text: string;
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof DocVisualExtendedField
     */
    FieldRect?: RectangleCoordinates;
    /**
     * Origin data group information. Only for Result.RFID_TEXT results.
     * @type {number}
     * @memberof DocVisualExtendedField
     */
    RFID_OriginDG?: number;
    /**
     * Index of the text field record in origin data group. Only for Result.RFID_TEXT results.
     * @type {number}
     * @memberof DocVisualExtendedField
     */
    RFID_OriginTagEntry?: number;
}


