/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ExtendedRfidTextField } from './extended-rfid-text-field';
import { ExtendedTextField } from './extended-text-field';
import { ExtendedVisualTextField } from './extended-visual-text-field';

/**
 * Container for extracted text fields. Fields are identified by type and language
 * @export
 * @interface DocVisualExtendedInfo
 */
export interface DocVisualExtendedInfo {
    /**
     * 
     * @type {Array<ExtendedTextField | ExtendedVisualTextField | ExtendedRfidTextField>}
     * @memberof DocVisualExtendedInfo
     */
    pArrayFields?: Array<ExtendedTextField | ExtendedVisualTextField | ExtendedRfidTextField>;
}


