/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DocVisualExtendedField } from './doc-visual-extended-field';

/**
 * Container for extracted text fields. Fields are identified by type and language
 * @export
 * @interface DocVisualExtendedInfo
 */
export interface DocVisualExtendedInfo {
    /**
     * 
     * @type {Array<DocVisualExtendedField>}
     * @memberof DocVisualExtendedInfo
     */
    pArrayFields: Array<DocVisualExtendedField>;
}


