/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Defining the geometric format of documents in accordance with ISO / IEC 7810
 * @export
 * @enum {string}
 */
export enum DocumentFormat {
    ID1 = 0,
    ID2 = 1,
    ID3 = 2,
    NON = 3,
    A4 = 4,
    ID3_X2 = 5,
    ID1_90 = 10,
    ID1_180 = 11,
    ID1_270 = 12,
    ID2_180 = 13,
    ID3_180 = 14,
    CUSTOM = 1000,
    FLEXIBLE = 1002
}



