/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DocumentTypeRecognitionResult } from './document-type-recognition-result';
import { OneCandidate } from './one-candidate';

/**
 * 
 * @export
 * @interface DocumentTypesCandidatesList
 */
export interface DocumentTypesCandidatesList {
    /**
     * 
     * @type {DocumentTypeRecognitionResult}
     * @memberof DocumentTypesCandidatesList
     */
    RecResult?: DocumentTypeRecognitionResult;
    /**
     * 
     * @type {Array<OneCandidate>}
     * @memberof DocumentTypesCandidatesList
     */
    Candidates?: Array<OneCandidate>;
}


