/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RectangleCoordinates } from './rectangle-coordinates';

/**
 * 
 * @export
 * @interface ExtendedVisualTextFieldAllOf
 */
export interface ExtendedVisualTextFieldAllOf {
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof ExtendedVisualTextFieldAllOf
     */
    FieldRect?: RectangleCoordinates;
}


