/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExtendedRfidTextFieldAllOf
 */
export interface ExtendedRfidTextFieldAllOf {
    /**
     * Information data group
     * @type {number}
     * @memberof ExtendedRfidTextFieldAllOf
     */
    RFID_OriginDG?: number;
    /**
     * Index of the text field record in information data group
     * @type {number}
     * @memberof ExtendedRfidTextFieldAllOf
     */
    RFID_OriginTagEntry?: number;
}


