/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ExtendedTextField } from './extended-text-field';
import { ExtendedVisualTextFieldAllOf } from './extended-visual-text-field-all-of';
import { LCID } from './lcid';
import { RectangleCoordinates } from './rectangle-coordinates';
import { StringRecognitionResult } from './string-recognition-result';
import { TextFieldType } from './text-field-type';

/**
 * @type ExtendedVisualTextField
 * @export
 */
export type ExtendedVisualTextField = ExtendedTextField & ExtendedVisualTextFieldAllOf;



