/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LCID } from './lcid';
import { StringRecognitionResult } from './string-recognition-result';
import { TextFieldType } from './text-field-type';

/**
 * 
 * @export
 * @interface ExtendedTextField
 */
export interface ExtendedTextField {
    /**
     * 
     * @type {TextFieldType}
     * @memberof ExtendedTextField
     */
    wFieldType?: TextFieldType;
    /**
     * 
     * @type {LCID}
     * @memberof ExtendedTextField
     */
    wLCID?: LCID;
    /**
     * Array of recognizing probabilities for a each line of text field
     * @type {Array<StringRecognitionResult>}
     * @memberof ExtendedTextField
     */
    StringsResult?: Array<StringRecognitionResult>;
    /**
     * Text field data in UTF8 format. Results of reading different lines of a multiline field are separated by “^”
     * @type {string}
     * @memberof ExtendedTextField
     */
    Buf_Text?: string;
}


