/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */
export enum FieldType {
    DOCUMENT_CLASS_CODE = 0,
    ISSUING_STATE_CODE = 1,
    DOCUMENT_NUMBER = 2,
    DATE_OF_EXPIRY = 3,
    DATE_OF_ISSUE = 4,
    DATE_OF_BIRTH = 5,
    PLACE_OF_BIRTH = 6,
    PERSONAL_NUMBER = 7,
    SURNAME = 8,
    GIVEN_NAME = 9,
    NATIONALITY = 11,
    SEX = 12,
    HEIGHT = 13,
    AUTHORITY = 24,
    SURNAME_AND_GIVEN_NAMES = 25,
    NATIONALITY_CODE = 26,
    MRZ_TYPE = 35,
    ISSUING_STATE_NAME = 38,
    MRZ_STRINGS = 51,
    DOCUMENT_NUMBER_CHECK_DIGIT = 80,
    DATE_OF_BIRTH_CHECK_DIGIT = 81,
    DATE_OF_EXPIRY_CHECK_DIGIT = 82,
    FINAL_CHECK_DIGIT = 84,
    CARD_ACCESS_NUMBER = 159,
    MRZ_STRINGS_WITH_CORRECT_CHECK_SUMS = 172,
    AGE = 185,
    REMAINDER_TERM = 364,
    AGE_AT_ISSUE = 522,
    YEARS_SINCE_ISSUE = 523
}



