/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */
export enum GraphicFieldType {
    PORTRAIT = 201,
    FINGERPRINT = 202,
    EYE = 203,
    SIGNATURE = 204,
    BAR_CODE = 205,
    PROOF_OF_CITIZENSHIP = 206,
    DOCUMENT_FRONT = 207,
    DOCUMENT_REAR = 208,
    COLOR_DYNAMIC = 209,
    GHOST_PORTRAIT = 210,
    STAMP = 211,
    OTHER = 250,
    FINGER_LEFT_THUMB = 300,
    FINGER_LEFT_INDEX = 301,
    FINGER_LEFT_MIDDLE = 302,
    FINGER_LEFT_RING = 303,
    FINGER_LEFT_LITTLE = 304,
    FINGER_RIGHT_THUMB = 305,
    FINGER_RIGHT_INDEX = 306,
    FINGER_RIGHT_MIDDLE = 307,
    FINGER_RIGHT_RING = 308,
    FINGER_RIGHT_LITTLE = 309
}



