/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GraphicFieldType } from './graphic-field-type';
import { ImageData } from './image-data';
import { RectangleCoordinates } from './rectangle-coordinates';

/**
 * 
 * @export
 * @interface GraphicField
 */
export interface GraphicField {
    /**
     * 
     * @type {GraphicFieldType}
     * @memberof GraphicField
     */
    FieldType: GraphicFieldType;
    /**
     * 
     * @type {ImageData}
     * @memberof GraphicField
     */
    image: ImageData;
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof GraphicField
     */
    FieldRect?: RectangleCoordinates;
    /**
     * Information data group. Only for Result.RFID_TEXT results.
     * @type {number}
     * @memberof GraphicField
     */
    RFID_OriginDG?: number;
    /**
     * Index of the source record of the image with biometric information in the information data group. Only for Result.RFID_TEXT results.
     * @type {number}
     * @memberof GraphicField
     */
    RFID_OriginDGTag?: number;
    /**
     * Index of the text field record in information data group. Only for Result.RFID_TEXT results.
     * @type {number}
     * @memberof GraphicField
     */
    RFID_OriginTagEntry?: number;
    /**
     * Biometric sample variant index. Only for Result.RFID_TEXT results.
     * @type {number}
     * @memberof GraphicField
     */
    RFID_OriginEntryView?: number;
}


