/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GraphicFieldType } from './graphic-field-type';
import { RawImageContainer } from './raw-image-container';
import { RectangleCoordinates } from './rectangle-coordinates';

/**
 * 
 * @export
 * @interface GraphicField
 */
export interface GraphicField {
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof GraphicField
     */
    FieldRect?: RectangleCoordinates;
    /**
     * 
     * @type {GraphicFieldType}
     * @memberof GraphicField
     */
    FieldType?: GraphicFieldType;
    /**
     * 
     * @type {RawImageContainer}
     * @memberof GraphicField
     */
    image?: RawImageContainer;
}


