/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Source } from './source';

/**
 * 
 * @export
 * @interface ImagesAvailableSource
 */
export interface ImagesAvailableSource {
    /**
     * Same as Result type, but used for safe parsing of not-described values. See Result type.
     * @type {number}
     * @memberof ImagesAvailableSource
     */
    containerType?: number;
    /**
     * 
     * @type {Source}
     * @memberof ImagesAvailableSource
     */
    source: Source;
}


