/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ImagesAvailableSource } from './images-available-source';
import { ImagesField } from './images-field';

/**
 * 
 * @export
 * @interface Images
 */
export interface Images {
    /**
     * 
     * @type {Array<ImagesAvailableSource>}
     * @memberof Images
     */
    availableSourceList: Array<ImagesAvailableSource>;
    /**
     * 
     * @type {Array<ImagesField>}
     * @memberof Images
     */
    fieldList: Array<ImagesField>;
}


