/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RectangleCoordinates } from './rectangle-coordinates';

/**
 * 
 * @export
 * @interface OriginalSymbol
 */
export interface OriginalSymbol {
    /**
     * Unicode symbol code
     * @type {number}
     * @memberof OriginalSymbol
     */
    code?: number;
    /**
     * Probability of correctness reading of a single character
     * @type {number}
     * @memberof OriginalSymbol
     */
    probability?: number;
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof OriginalSymbol
     */
    rect?: RectangleCoordinates;
}


