/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.  # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 5.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PerDocumentConfig
 */
export interface PerDocumentConfig {
    /**
     * Specific template IDs, for which apply current custom configuration
     * @type {Array<number>}
     * @memberof PerDocumentConfig
     */
    docID?: Array<number>;
    /**
     * Contains items from AuthenticityResultType as sum via OR operation
     * @type {number}
     * @memberof PerDocumentConfig
     */
    excludeAuthChecks?: number;
}


