/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProcessSystemInfo
 */
export interface ProcessSystemInfo {
    /**
     * Base64 encoded license file
     * @type {string}
     * @memberof ProcessSystemInfo
     */
    license?: string;
    /**
     * For internal use. Demo-sites recaptcha token.
     * @type {string}
     * @memberof ProcessSystemInfo
     */
    recaptcha_token?: string;
}


