/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ProcessParams } from './process-params';
import { ProcessRequestImage } from './process-request-image';
import { ProcessSystemInfo } from './process-system-info';

/**
 * 
 * @export
 * @interface ProcessRequest
 */
export interface ProcessRequest {
    /**
     * 
     * @type {ProcessParams}
     * @memberof ProcessRequest
     */
    processParam: ProcessParams;
    /**
     * 
     * @type {Array<ProcessRequestImage>}
     * @memberof ProcessRequest
     */
    List: Array<ProcessRequestImage>;
    /**
     * 
     * @type {ProcessSystemInfo}
     * @memberof ProcessRequest
     */
    systemInfo?: ProcessSystemInfo;
}


