/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ContainerList } from './container-list';
import { ProcessingStatus } from './processing-status';
import { RfidLocation } from './rfid-location';
import { TransactionInfo } from './transaction-info';

/**
 * 
 * @export
 * @interface ProcessResponse
 */
export interface ProcessResponse {
    /**
     * 
     * @type {RfidLocation}
     * @memberof ProcessResponse
     */
    ChipPage: RfidLocation;
    /**
     * 
     * @type {ProcessingStatus}
     * @memberof ProcessResponse
     */
    ProcessingFinished: ProcessingStatus;
    /**
     * 
     * @type {ContainerList}
     * @memberof ProcessResponse
     */
    ContainerList: ContainerList;
    /**
     * 
     * @type {TransactionInfo}
     * @memberof ProcessResponse
     */
    TransactionInfo: TransactionInfo;
}


