/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RawImageContainer
 */
export interface RawImageContainer {
    /**
     * 
     * @type {string}
     * @memberof RawImageContainer
     */
    format?: string;
    /**
     * base64 encoded image
     * @type {string}
     * @memberof RawImageContainer
     */
    image?: string;
}


