/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Coordinates of the rectangle region in the normalized image of the document
 * @export
 * @interface RectangleCoordinates
 */
export interface RectangleCoordinates {
    /**
     * 
     * @type {number}
     * @memberof RectangleCoordinates
     */
    left: number;
    /**
     * 
     * @type {number}
     * @memberof RectangleCoordinates
     */
    top: number;
    /**
     * 
     * @type {number}
     * @memberof RectangleCoordinates
     */
    right: number;
    /**
     * 
     * @type {number}
     * @memberof RectangleCoordinates
     */
    bottom: number;
}


