/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Determines the presence and location of an RFID chip in a document
 * @export
 * @enum {string}
 */
export enum RfidLocation {
    NONE = 0,
    MAIN_PAGE = 1,
    BACK_PAGE = 2
}



