/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.  # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 6.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Enumeration contains identifiers determining type of features for a document authenticity checks
 * @export
 * @enum {string}
 */
export enum SecurityFeatureType {
    BLANK = 0,
    FILL = 1,
    PHOTO = 2,
    MRZ = 3,
    FALSE_LUMINESCENCE = 4,
    HOLO_SIMPLE = 5,
    HOLO_VERIFY_STATIC = 6,
    HOLO_VERIFY_MULTI_STATIC = 7,
    HOLO_VERIFY_DYNAMIC = 8,
    PATTERN_NOT_INTERRUPTED = 9,
    PATTERN_NOT_SHIFTED = 10,
    PATTERN_SAME_COLORS = 11,
    PATTERN_IR_INVISIBLE = 12,
    PHOTO_SIZE_CHECK = 13,
    PORTRAIT_COMPARISON_VS_GHOST = 14,
    PORTRAIT_COMPARISON_VS_RFID = 15,
    PORTRAIT_COMPARISON_VS_VISUAL = 16,
    BARCODE = 17,
    PATTERN_DIFFERENT_LINES_THICKNESS = 18,
    PORTRAIT_COMPARISON_VS_CAMERA = 19,
    PORTRAIT_COMPARISON_RFID_VS_CAMERA = 20,
    GHOST_PHOTO = 21,
    CLEAR_GHOST_PHOTO = 22,
    INVISIBLE_OBJECT = 23,
    LOW_CONTRAST_OBJECT = 24,
    PHOTO_COLOR = 25,
    PHOTO_SHAPE = 26,
    PHOTO_CORNERS = 27,
    PORTRAIT_COMPARISON_EXT_VS_VISUAL = 29,
    PORTRAIT_COMPARISON_EXT_VS_RFID = 30,
    PORTRAIT_COMPARISON_EXT_VS_CAMERA = 31
}



