/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Document data sources
 * @export
 * @enum {string}
 */
export enum Source {
    MRZ = 'MRZ',
    VISUAL = 'VISUAL',
    BARCODE = 'BARCODE',
    RFID = 'RFID',
    MAGNETIC = 'MAGNETIC'
}



