/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Documents recognition as easy as reading two bytes.  # Clients: * [JavaScript](https://github.com/regulaforensics/DocumentReader-web-js-client) client for the browser and node.js based on axios * [Java](https://github.com/regulaforensics/DocumentReader-web-java-client) client compatible with jvm and android * [Python](https://github.com/regulaforensics/DocumentReader-web-python-client) 3.5+ client * [C#](https://github.com/regulaforensics/DocumentReader-web-csharp-client) client for .NET & .NET Core 
 *
 * The version of the OpenAPI document: 6.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CheckResult } from './check-result';
import { DetailsOptical } from './details-optical';
import { DetailsRFID } from './details-rfid';

/**
 * 
 * @export
 * @interface Status
 */
export interface Status {
    /**
     * 
     * @type {CheckResult}
     * @memberof Status
     */
    overallStatus: CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof Status
     */
    optical: CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof Status
     */
    portrait?: CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof Status
     */
    rfid?: CheckResult;
    /**
     * 
     * @type {CheckResult}
     * @memberof Status
     */
    stopList?: CheckResult;
    /**
     * 
     * @type {DetailsRFID}
     * @memberof Status
     */
    detailsRFID?: DetailsRFID;
    /**
     * 
     * @type {DetailsOptical}
     * @memberof Status
     */
    detailsOptical: DetailsOptical;
}


