/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Describes the result of recognizing an individual character in the string field of the document
 * @export
 * @interface SymbolCandidate
 */
export interface SymbolCandidate {
    /**
     * ASCII symbol code
     * @type {number}
     * @memberof SymbolCandidate
     */
    SymbolCode?: number;
    /**
     * character recognition probability (0–100,%)
     * @type {number}
     * @memberof SymbolCandidate
     */
    SymbolProbability?: number;
}


