/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OriginalSymbol } from './original-symbol';
import { RectangleCoordinates } from './rectangle-coordinates';
import { RfidOrigin } from './rfid-origin';
import { Source } from './source';

/**
 * 
 * @export
 * @interface TextFieldValue
 */
export interface TextFieldValue {
    /**
     * 
     * @type {Source}
     * @memberof TextFieldValue
     */
    source: Source;
    /**
     * Parsed/processed value. Date format converted for output, delimiters removed
     * @type {string}
     * @memberof TextFieldValue
     */
    value: string;
    /**
     * Original value as seen in the document
     * @type {string}
     * @memberof TextFieldValue
     */
    originalValue?: string;
    /**
     * 
     * @type {Array<OriginalSymbol>}
     * @memberof TextFieldValue
     */
    originalSymbols?: Array<OriginalSymbol>;
    /**
     * Page index of the image from input list
     * @type {number}
     * @memberof TextFieldValue
     */
    pageIndex: number;
    /**
     * Min recognition probability. Combined minimum probability from single characters probabilities
     * @type {number}
     * @memberof TextFieldValue
     */
    probability?: number;
    /**
     * 
     * @type {RectangleCoordinates}
     * @memberof TextFieldValue
     */
    fieldRect?: RectangleCoordinates;
    /**
     * 
     * @type {RfidOrigin}
     * @memberof TextFieldValue
     */
    rfidOrigin?: RfidOrigin;
}


