/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader Web API
 * Regula Document Reader Web API
 *
 * The version of the OpenAPI document: 5.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TransactionInfo
 */
export interface TransactionInfo {
    /**
     * 
     * @type {string}
     * @memberof TransactionInfo
     */
    ComputerName?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionInfo
     */
    DateTime?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionInfo
     */
    TransactionID?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionInfo
     */
    UserName?: string;
}


