/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader SDK Web API
 * Regula Document Reader SDK Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./ext/index.js";
export * from "./configuration.js";

export * from './models/area-container.js';
export * from './models/authenticity-check-list.js';
export * from './models/authenticity-check-result.js';
export * from './models/authenticity-check-result-item.js';
export * from './models/authenticity-result.js';
export * from './models/authenticity-result-all-of.js';
export * from './models/check-diagnose.js';
export * from './models/check-result.js';
export * from './models/chosen-document-type.js';
export * from './models/chosen-document-type-result.js';
export * from './models/chosen-document-type-result-all-of.js';
export * from './models/container-list.js';
export * from './models/critical.js';
export * from './models/cross-source-value-comparison.js';
export * from './models/details-optical.js';
export * from './models/details-rfid.js';
export * from './models/device-info.js';
export * from './models/doc-visual-extended-field.js';
export * from './models/doc-visual-extended-info.js';
export * from './models/document-format.js';
export * from './models/document-image.js';
export * from './models/document-image-result.js';
export * from './models/document-image-result-all-of.js';
export * from './models/document-type.js';
export * from './models/document-type-recognition-result.js';
export * from './models/document-types-candidates.js';
export * from './models/document-types-candidates-list.js';
export * from './models/document-types-candidates-result.js';
export * from './models/document-types-candidates-result-all-of.js';
export * from './models/fdsidlist.js';
export * from './models/fiber-result.js';
export * from './models/fiber-result-all-of.js';
export * from './models/graphic-field.js';
export * from './models/graphic-field-type.js';
export * from './models/graphic-fields-list.js';
export * from './models/graphics-result.js';
export * from './models/graphics-result-all-of.js';
export * from './models/ident-result.js';
export * from './models/ident-result-all-of.js';
export * from './models/image-data.js';
export * from './models/image-qa.js';
export * from './models/images-available-source.js';
export * from './models/images-field-value.js';
export * from './models/images-result.js';
export * from './models/images-result-all-of.js';
export * from './models/lcid.js';
export * from './models/lexical-analysis-result.js';
export * from './models/lexical-analysis-result-all-of.js';
export * from './models/light.js';
export * from './models/list-verified-fields.js';
export * from './models/ocrsecurity-text-result.js';
export * from './models/ocrsecurity-text-result-all-of.js';
export * from './models/one-candidate.js';
export * from './models/original-symbol.js';
export * from './models/photo-ident-result.js';
export * from './models/photo-ident-result-all-of.js';
export * from './models/point.js';
export * from './models/points-container.js';
export * from './models/process-params.js';
export * from './models/process-response.js';
export * from './models/process-system-info.js';
export * from './models/processing-status.js';
export * from './models/raw-image-container-list.js';
export * from './models/rectangle-coordinates.js';
export * from './models/result.js';
export * from './models/result-item.js';
export * from './models/rfid-location.js';
export * from './models/rfid-origin.js';
export * from './models/scenario.js';
export * from './models/security-feature-result.js';
export * from './models/security-feature-result-all-of.js';
export * from './models/security-feature-type.js';
export * from './models/source.js';
export * from './models/source-validity.js';
export * from './models/status.js';
export * from './models/status-result.js';
export * from './models/status-result-all-of.js';
export * from './models/string-recognition-result.js';
export * from './models/symbol-candidate.js';
export * from './models/symbol-recognition-result.js';
export * from './models/text-available-source.js';
export * from './models/text-data-result.js';
export * from './models/text-data-result-all-of.js';
export * from './models/text-field-type.js';
export * from './models/text-field-value.js';
export * from './models/text-result.js';
export * from './models/text-result-all-of.js';
export * from './models/transaction-info.js';
export * from './models/verification-result.js';
export * from './models/verified-field-map.js';
export * from './models/visibility.js';