/* tslint:disable */
/* eslint-disable */
/**
 * Regula Document Reader SDK Web API
 * Regula Document Reader SDK Web API
 *
 * The version of the OpenAPI document: 5.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./ext/index.js";
export * from "./configuration.js";

export * from './models/available-source.js';
export * from './models/barcode-text-data-result.js';
export * from './models/check-result.js';
export * from './models/chosen-document-type-result.js';
export * from './models/chosen-document-type-result-all-of.js';
export * from './models/container-list.js';
export * from './models/cross-source-value-comparison.js';
export * from './models/doc-visual-extended-info.js';
export * from './models/document-format.js';
export * from './models/document-type.js';
export * from './models/document-type-recognition-result.js';
export * from './models/document-types-candidates-list.js';
export * from './models/document-types-candidates-result.js';
export * from './models/document-types-candidates-result-all-of.js';
export * from './models/extended-rfid-text-field.js';
export * from './models/extended-rfid-text-field-all-of.js';
export * from './models/extended-text-field.js';
export * from './models/extended-visual-text-field.js';
export * from './models/extended-visual-text-field-all-of.js';
export * from './models/graphic-field.js';
export * from './models/graphic-field-type.js';
export * from './models/graphic-fields-list.js';
export * from './models/graphics-result.js';
export * from './models/graphics-result-all-of.js';
export * from './models/image-data.js';
export * from './models/lcid.js';
export * from './models/lexical-analysis-result.js';
export * from './models/lexical-analysis-result-all-of.js';
export * from './models/light.js';
export * from './models/list-verified-fields.js';
export * from './models/mrz-ocr-extended-result.js';
export * from './models/mrz-ocr-extended-result-all-of.js';
export * from './models/one-candidate.js';
export * from './models/process-params.js';
export * from './models/process-response.js';
export * from './models/processing-status.js';
export * from './models/raw-image-container.js';
export * from './models/raw-image-result.js';
export * from './models/raw-image-result-all-of.js';
export * from './models/rectangle-coordinates.js';
export * from './models/result.js';
export * from './models/result-item.js';
export * from './models/rfid-location.js';
export * from './models/rfid-text-data-result.js';
export * from './models/scenario.js';
export * from './models/source.js';
export * from './models/source-validity.js';
export * from './models/string-recognition-result.js';
export * from './models/symbol-candidate.js';
export * from './models/symbol-recognition-result.js';
export * from './models/tfdsidlist.js';
export * from './models/text-field-type.js';
export * from './models/text-field-value.js';
export * from './models/text-result.js';
export * from './models/text-result-all-of.js';
export * from './models/transaction-info.js';
export * from './models/verification-result.js';
export * from './models/verified-field-map.js';
export * from './models/visual-ocr-extended-result.js';